LOCAL_MB_ROOT = ".mb"
LOCAL_INBOX_DIRNAME = "inbox"
LOCAL_OUTBOX_DIRNAME = "outbox"
LOCAL_MB_LOGS_ROOT = "logs"
LOCAL_MB_LOGS_BUILD_DIRNAME = "build"
LOCAL_ENV_DIRNAME = "env"
LOCAL_ENV_SELECT_FILENAME = ".selected"
LOCAL_LIB_SELECT_FILENAME = ".selected"

DEFAULT_ENV_CONFIG_NAME = "default" # Maybe this should be "develop"?

DEFAULT_LIBRARY_NAME = 'default'

PIPELINE_CONTAINERFILE_SEPARATOR = ':'
PIPELINE_CONTAINERFILE_OS_WINDOWS = "windows"
PIPELINE_CONTAINERFILE_OS_LINUX = "linux"
